user_info = {
    'id': 'FSCPIb0tSUCALc_aagxmlg', 
    'first_name': 'Hridesh', 
    'last_name': 'Sharma', 
    'display_name': 'Hridesh Sharma', 
    'email': 'hridesh.s@consultadd.com', 
    'type': 1, 
    'role_name': 'Owner', 
    'pmi': 0, 
    'use_pmi': False, 
    'personal_meeting_url': '', 
    'timezone': '', 
    'verified': 0, 
    'dept': '', 
    'created_at': '2023-01-10T15:14:54Z', 
    'last_login_time': '2023-01-12T07:15:26Z', 
    'pic_url': 'https://zoom.us/p/FSCPIb0tSUCALc_aagxmlg/8d4a193f-4905-48cc-a376-4b7f5ad84a81-9398', 
    'cms_user_id': '', 
    'jid': 'fscpib0tsucalc_aagxmlg@xmpp.zoom.us', 
    'group_ids': [], 
    'im_group_ids': [], 
    'account_id': 'Rb1G3LUtSCKgmOZcGmQiGA', 
    'language': 'en-US', 
    'phone_country': '', 
    'phone_number': '', 
    'status': 'active', 
    'job_title': '', 
    'location': '', 
    'login_types': [1], 
    'role_id': '0', 
    'account_number': 7034228485, 
    'cluster': 'aw1', 
    'user_created_at': '2023-01-10T15:14:54Z'
}